# Generated by Django 4.1.5 on 2023-02-02 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Home", "0003_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="aadhaar",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="profile",
            name="pan",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="profile",
            name="tax_slab",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
