# Generated by Django 4.1.5 on 2023-02-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0004_profile_aadhaar_profile_full_name_profile_pan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
    ]
