# Generated by Django 4.1.5 on 2023-02-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0005_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.webp", upload_to="profile_pics"),
        ),
    ]
